swagger: '2.0'
info:
  version: '1.0'
  title: "nestareas"
  description: A simple way to manage the common areas within NEST - Nuovo Studentato Trento
  license:
    name: MIT
    url: https://github.com/Facco/se
host: localhost
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /login/{mail}:
    get:
      summary: Login
      description: Authenticates the user.
      parameters:
        - in: path
          name: mail
          required: true
          type: string
          minimum: 1
          description: The mail of the user you want to authenticate.
        - in: query
          name: password
          required: true
          type: string
          minimum: 1
          description: The password of the user you want to authenticate.
      responses:
        200:
          description: A response Object.
          schema:
            type: object
            properties:
              logged:
                type: boolean
                description: The authentication was successfull or not.
              authToken:
                type: string
                description: The authentication token generated by the server.
        301:
          description: A response Object.
          schema:
            type: object
            properties:
              logged:
                type: boolean
                description: The authentication was successfull or not.
              errorDescription:
                type: string
                description: The description of the error occurred.
          
        
  
